repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check
        language: system
        types: [python]
        files: .
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: .